# Generated by Django 4.1.5 on 2023-05-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_bio_user_name_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avater',
            field=models.TextField(default='avater.svg', null=True),
        ),
    ]
